### ISSUE TITLE
The benchmark service seems to be down

### ISSUE THREAD

**Issue by kunalchelani** [WaldJohannaU/RIO10#11]
The benchmark service at https://vmnavab26.in.tum.de/RIO10/benchmarks.php seems to be down. Any idea when will it be back?

**Comment by Shubodh** [comment]
It has been down for a long time. I had emailed the primary author as well as other authors. They are not responding sadly :(

I want to look at the benchmark and accordingly write my paper but it's on hold now for the same reason :disappointed:

**Comment by Shubodh** [comment]
Thank you for your interest in the RIO10 benchmark. 

We are working on this issue and will update you the moment we fix it. Apologies.

**Comment by Shubodh** [comment]
It is up and running now. Closing this issue.
