### ISSUE TITLE
About instance segmentation

### ISSUE THREAD

**Issue by luzai** [WaldJohannaU/RIO10#3]
Hi, Thank you very much for sharing ROI10! 

In the paper, you mention that the ground-truth 2D instance segmentations are generated for each RGB frame. May I ask how to visualize or use this side information? 

Thank you!

**Comment by WaldJohannaU** [comment]
We used the [renderer](https://github.com/WaldJohannaU/3RScan/tree/master/c++/rio_renderer) of 3RScan to generate 2D ground truth instance segmentations.

I added the semantics (for the train and validation sequence) to the download script. We however don't plan to release the 2D ground truth segmentation of the hidden test set.
