### ISSUE TITLE
Color mapping between instances.txt and labels.ply

### ISSUE THREAD

**Issue by piljoong-jeong** [WaldJohannaU/RIO10#5]
Hello, first of all thank you for sharing this amazing dataset! 
I'm writing this issue to know how the color mappings between instances.txt and the vertex color in labels.ply are made. 

Specifically, I want to extract vertex positions of 'bag' given instances.txt and corresponding labels.ply; 
![image](https://user-images.githubusercontent.com/43630935/112707101-0effc000-8eec-11eb-94a7-93862b058265.png)
by referring this I tried to grab vertices of bag in the mesh;
![image](https://user-images.githubusercontent.com/43630935/112707127-3bb3d780-8eec-11eb-82c2-4e99016a5e76.png)

It would be easily solved if the mappings between 1D label index (2, 3, 4) to 3D false-coded color of bag's vertex positions are known, but it's not that easy than I expected. 

Any helps are appreciated. Thanks!

**Comment by piljoong-jeong** [comment]
So during weekends I delved into how to easily get the mappings, but I ended up with it is impossible to know (please correct me if I am wrong)

I guessed that RIO10 dataset is highly related to 3RScan's one, which is predecessor of the project. After digging the code I found the function named RIO::InitGlobalId2Color(~), which seems accept the amount of existing objects in the scene and falsely colors them.

If assuming labels.ply is the output of this function, due to the existence of random sampling function (std::rand), we cannot know the exact mappings between object and resulting color.

```cpp
void RIO::InitGlobalId2Color(const int size) {
    // let's fix the seed to make sure we always get the same colors.
    std::srand(0);
    // instance with index 0 is invalid.
    globalId2color.push_back(Eigen::Vector3i(0,0,0));
    for (int i = 0; i < size; i++) {
    	const int b = std::rand() % (color_range_from - color_range_to) + color_range_from;
        const int g = std::rand() % (color_range_from - color_range_to) + color_range_from;
        const int r = std::rand() % (color_range_from - color_range_to) + color_range_from;
        globalId2color.push_back(Eigen::Vector3i(r,g,b));
    }
}
```

If it is possible to remap current labels.ply the problem will be solved. (by recording the pairs of object & resulting color)

Another hacky way is find known object's vertex color manually.
![image](https://user-images.githubusercontent.com/43630935/112773946-fb329600-9072-11eb-9928-c911c86e97c3.png)

Above is the example of finding colors of object 'ironing board'. Since we know that every vertex color of an object is same, we can try picking specific vertices by using external toolkits (here, Meshlab is used)

**Comment by piljoong-jeong** [comment]
One-line summary: failed to reproduce exact color, and I think it is because the compiler is different from the one used to generating dataset

I found that the color is shared if objects across the scene have same label index (of course it should be true according to the implementation: only index is the variable)

For example, consider 16th index of instances.txt; floor in scene01, trash can in scene02. Although they are totally different object, they have same color [188, 189, 34] since the index is same.

scene01 (floor)
![image](https://user-images.githubusercontent.com/43630935/112779974-d3e3c500-9082-11eb-9dfc-90559018ca53.png)

scene02 (trash can)
![image](https://user-images.githubusercontent.com/43630935/112779909-b44c9c80-9082-11eb-8bee-e6f431091af3.png)

However, reproducing color is failed even the implementation is same, and I guess it is because the compiler used to generate dataset is different from mine.
(random algorithms are highly dependent to platform / compiler implementation etc)

In my implementation, index 16 gives [100 238 233], which is far different to [188 189 34]

**Comment by WaldJohannaU** [comment]
Hi @piljoong-jeong,

you are right, the colors in the ply are random across different instances and scenes, they correspond to the instance ID. The easiest way to get the mapping is to use the custom properties in the ply (objectId) or the semantics directly (NYU40, globalId):

```
property float x
property float y
property float z
property uchar red
property uchar green
property uchar blue
property ushort objectId
property ushort globalId
property uchar NYU40
property uchar Eigen13
property uchar RIO27
```

hope that helps!

**Comment by piljoong-jeong** [comment]
Appreciate for the reply! With properties I've achieved to grab specific objects' pixel values.

I found another strange point in instances.txt, that I thought if the scene is identical (i.e., located in same real space) the labels should be also identical. However there're some minor differences between instances.txt:

scene01/seq01_01/instances.txt;
```bash
1 washing basket
2 bag
3 bag
4 bag
5 washing basket
6 box
7 box
8 cupboard
9 cupboard
10 object
11 shelf
12 object
13 shelf
14 clutter
15 clutter
16 floor
17 wall
18 wall
19 wall
20 washing machine
21 wall
22 sink
23 mirror
24 ceiling
25 ironing board
26 ironing board
27 washing basket
28 window
29 window
30 radiator
31 garbage bin
32 washing basket
33 chair
34 box
35 door
36 box
37 hand brush
38 washing powder
39 pipe
```

scene01/seq01_02/instances.txt
```bash
1 washing basket
2 bag
3 bag
4 bag
5 washing basket
6 box
7 box
8 cupboard
9 cupboard
10 object
11 shelf
12 object
13 shelf
14 clutter
16 floor
17 wall
18 wall
19 wall
20 washing machine
21 wall
22 sink
23 mirror
24 ceiling
25 ironing board
26 ironing board
27 washing basket
28 window
29 window
30 radiator
31 garbage bin
32 washing basket
33 chair
34 box
35 door
36 box
37 hand brush
38 washing powder
```

some objectId are removed (e.g. "15 cluttered" and "39 pipe" from seq01_01).
In this case which instances.txt is correct? Will it be OK to use either from those?
Where those difference comes from? Is this the limitation of automated instance segmentation algorithm?

**Comment by WaldJohannaU** [comment]
The instances are not identical since some objects disappear or appear over time (or simply not be visible in one of the scans) but the IDs are consistent e.g. washing basket 32 is the same object in both scans. You need to use the corresponding instances.txt of each scan.

Our instances are manually annotated by humans in 3D but rely on a prior automatic segmentation of the scene. Segmentation masks of very flat and small objects are challenging and therefore sometimes missed.

**Comment by piljoong-jeong** [comment]
Thanks for clarification! Question resolved, closing the issue.
