### ISSUE TITLE
Request for Access

### ISSUE THREAD

**Issue by EduardoFraguas** [WaldJohannaU/RIO10#7]
I have been trying to download RIO10 dataset but it has been impossible, I've recived "404 Not Found" "nginx/1.18.0 (Ubuntu) every time I've tried to access the link. 

How could I get access to your dataset, is it publicly accessible?

**Comment by WaldJohannaU** [comment]
sorry for the late response. We had issues with our lab server and had to migrate all the datasets which took longer than expected. The new server with corresponding certificates is now finally ready to be used.

You should get the updated link if you edit/fill out the request form.
